language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
env:
  - DB=postgresql
before_install:
  - cp spec/config.travis.yml spec/config.yml
  - psql -c 'create database textacular_test' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake
gemfile:
  - Gemfile
  - gemfiles/activerecord-5.0.gemfile
  - gemfiles/activerecord-5.1.gemfile
